### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by marijaantic** [sugarshin/react-instagram-embed#31] opened 2018-10-29 08:27 UTC
**Bug noticed on live demo:** https://sugarshin.github.io/react-instagram-embed/

**Comment by yu-imu** [comment] 2018-10-29 11:57
My application is also faced this bug.
This bug may be caused by CORB.
> search console
![screen shot 2018-10-28 at 22 59 50](https://user-images.githubusercontent.com/17560599/47648304-fecd4480-dbbc-11e8-9a84-0caeca783d9e.png)

**Comment by khairendra** [comment] 2018-10-30 04:47
Yup, i also experienced this problem.
Probably because of the callback ?

in firefox if you access directly

`https://api.instagram.com/oembed/?hidecaption=false&maxwidth=320&omitscript=true&url=https%3A%2F%2Finstagr.am%2Fp%2FZw9o4%2F`

without the callback, it correctly return js object.

but if you also include the callback like
`https://api.instagram.com/oembed/?hidecaption=false&maxwidth=320&omitscript=true&url=https%3A%2F%2Finstagr.am%2Fp%2FZw9o4%2F&callback=__jp0`,

it return `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by hugovk** [comment] 2018-10-30 14:23
Here's a PR to fix it: https://github.com/sugarshin/react-instagram-embed/pull/32.

**Comment by JokinenK** [comment] 2018-10-31 11:02
Before this PR gets merged or bug fixed in some other way, here is easy way to test the PR's changes out:

npm install --save git+https://github.com/JokinenK/react-instagram-embed#release/1.4.0_json

or 

yarn add git+https://github.com/JokinenK/react-instagram-embed#release/1.4.0_json

**Comment by sugarshin** [comment] 2018-11-04 03:53
I solved and released new version.

**Closed by sugarshin** 2018-11-04 03:53 UTC
